// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	zapcore "go.uber.org/zap/zapcore"
)

// ICMDExecutor is an autogenerated mock type for the ICMDExecutor type
type ICMDExecutor struct {
	mock.Mock
}

// CreateDirectory provides a mock function with given fields: path, zf
func (_m *ICMDExecutor) CreateDirectory(path string, zf ...zapcore.Field) error {
	_va := make([]interface{}, len(zf))
	for _i := range zf {
		_va[_i] = zf[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, path)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, ...zapcore.Field) error); ok {
		r0 = rf(path, zf...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExecuteCommand provides a mock function with given fields: binaryName, args, zf
func (_m *ICMDExecutor) ExecuteCommand(binaryName string, args []string, zf ...zapcore.Field) ([]string, error) {
	_va := make([]interface{}, len(zf))
	for _i := range zf {
		_va[_i] = zf[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, binaryName, args)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 []string
	if rf, ok := ret.Get(0).(func(string, []string, ...zapcore.Field) []string); ok {
		r0 = rf(binaryName, args, zf...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, []string, ...zapcore.Field) error); ok {
		r1 = rf(binaryName, args, zf...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewICMDExecutor interface {
	mock.TestingT
	Cleanup(func())
}

// NewICMDExecutor creates a new instance of ICMDExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewICMDExecutor(t mockConstructorTestingTNewICMDExecutor) *ICMDExecutor {
	mock := &ICMDExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
